remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme
title: "Algorist"
description: "Algorithmic art generation in Blender"
show_downloads: false
defaults:
  - scope:
      path: "renders"
    values:
      render: true
