name: Render
on: [push]

jobs:
  render:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Install Blender
      run: |
        sudo snap install blender --channel=3.0/stable --classic
    - name: Get branch
      run: |
        # Short name for current branch. For PRs, use target branch (base ref)
        GIT_BRANCH=${GITHUB_BASE_REF:-${GITHUB_REF#refs/heads/}}
        echo "GIT_BRANCH=$GIT_BRANCH" >> $GITHUB_ENV
    - name: Render
      run: |
        if [ "$GIT_BRANCH" != "master" ]; then
          sed -i -e s/640/80/ -e s/360/45/ .github/workflows/resolution.py
        fi
        mkdir /tmp/renders
        for py in examples/*.py; do
          hash=$(sha1sum $py | cut -d ' ' -f 1)
          ./algorist.sh $py --python .github/workflows/resolution.py --background --engine CYCLES --render-format PNG --use-extension 1 --render-output "/tmp/renders/$(basename $py).#.$hash" --render-frame 1 -- --cycles-device CPU
        done
    - name: Upload renders
      if: env.GIT_BRANCH == 'master'
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git checkout gh-pages
        git clean -d -f
        # Copy images unless they already exist (don't want to re-render images that have randomized contents)
        rsync --recursive --ignore-existing --delete /tmp/renders/ renders/
        git add renders
        if git commit -m "new renders"; then
          git push
        fi
