name: Render
on:
  push:
  workflow_dispatch:

jobs:
  render:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Install Blender
      run: |
        sudo snap install blender --channel=3.0/stable --classic
    - name: Render
      run: |
        # lowrez if we aren't publishing
        if [ "${{ github.event_name }}" != "workflow_dispatch" ]; then
          sed -i -e s/640/80/ -e s/360/45/ .github/workflows/resolution.py
        fi
        mkdir /tmp/renders
        for py in examples/*.py; do
          ./algorist.sh $py --python .github/workflows/resolution.py --background --engine CYCLES --render-format PNG --use-extension 1 --render-output "/tmp/renders/$(basename $py).#" --render-frame 1 -- --cycles-device CPU
        done
    - name: Upload renders
      if: ${{ github.event_name == 'workflow_dispatch' }}
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git checkout gh-pages
        git clean -d -f
        rm -f renders/*
        cp /tmp/renders/* renders/
        git add renders
        if git commit -m "new renders"; then
          git push
        fi
